#!/usr/bin/env php

<?php

ini_set('memory_limit', -1);

/**
 * @file
 * Application entrypoint for the migration framework.
 */

foreach ([__DIR__ . '/../../../vendor/autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
  if (file_exists($file)) {
    require $file;
    break;
  }
}

use Symfony\Component\Console\Application;
use Merlin\Command\GenerateCommand;
use Merlin\Command\CrawlCommand;
use Merlin\Command\CacheCommand;
use Merlin\Command\ReportCommand;

/**
 * Defines a useful global function to do a var_dump to error_log
 *
 * @param null $object
 */
function var_error_log($object = null)
{
    ob_start();                    // start buffer capture
    var_dump($object);             // dump the values
    $contents = ob_get_contents(); // put the buffer into a variable
    ob_end_clean();                // end capture
    error_log($contents);          // log contents of the result of var_dump( $object )
}

$application = new Application;

$application->add(new GenerateCommand);
$application->add(new CrawlCommand);
$application->add(new CacheCommand);
$application->add(new ReportCommand);

$application->run();
